Fixed bug causing bokeh plot to break
On a fresh install of bokeh 3.3.0 the using plot_width and plot_height results in the following errors:

AttributeError: unexpected attribute 'plot_width' to figure, similar attributes are outer_width, width or min_width